### ISSUE TITLE
[Question] Eliminating the pause when updating

### ISSUE THREAD

**Issue by HajimeSait0** [Kamikaze94/Enhanced-Fast.Net#2]
This is, as I'm trying to illustrate in the title, more a question than anything else. The Fast.Net Standalone made by GREAT BIG BUSHY BEARD didn't have the annoying lag that occured when updating the list of servers. I'm frankly unsure of what causes it, but I was curious if it's something you encountered and were unable to work out of the enhanced version.

**Comment by Kamikaze94** [comment]
Well, after some trial and error, I found out, the freeze is caused by my addition of marking your friends lobbies in FastNet. It fetched your friends everytime again, and that needs some time, thus resulting in a short freeze. Changed it now, so it caches your friendslist on the core file being loaded. Therefore, a recently added friend will not show up as one, until your game is restarted or you start a day/join a lobby/do anything that reloads the mod. But I guess it's not that much of a disadvantage.

_(Btw, I never really payed attention to that lag, and thought it was caused by the game fetching the lobby data from steam. Seems like I was wrong, :P )_

When I was at it, I added some basic sorting to lobbies by the number of current players in the lobby and (hopefully) fixed the bug of currently online players appearing in the main menu sometimes, when you open and close FastNet Friends multiple times.

I know, I'm not doing much with this mod, and I'm wondering, if there are more that 10 people around using it, lol.
Anyways, I hope you apprechiate the update/changes, and if you notice other problems/bugs, feel free to tell me, and I'll see what I can do.

**EDIT:** Just changed the sorting function to what I originally intended:
It will sort primarily by difficulty from low to high.
It will sort secondarily by the amount of players in that lobby.
I like it ;)

**Comment by HajimeSait0** [comment]
Brilliant! I'm giving it a try now, and suggesting it to a friend as we speak. I had a suggestion for the problem of recently added friends not showing up in the list. I know the Fast.Net Friends function was added by another user's request, but what if there were an option in the Friends menu to update the friendlist cache?

My first thought was to make it work much like the general menu's G to Update function. Or maybe automatically when you enter the Friends menu. But honestly, you've done more than enough in my book, so take or leave that suggestion. Seriously, thank you so much for working on this still!

EDIT: Took a second look at your post, I didn't actually notice something as simple as starting a heist or joining a lobby would recache it. Fantastic work!
